---
- hosts: app_server
  become: yes 
  tasks:
     - name: install apache server
       yum:
         name: httpd
         state : latest
       tags:
          apache

     - name: remove the Apache package
       yum:
         name: httpd
         state: absent
       tags:
          apache
